### ISSUE TITLE
Error with 405 status code after Vercel Deploy

### ISSUE THREAD

**Issue by GabrielRoc** [okisdev/ChatChat#167] opened 2023-08-04 04:52 UTC
https://chat.gabrielrocha.tech/

after deploying to vercel the api endpoints are returning 405 making it impossible to use

**Comment by okisdev** [comment] 2023-08-04 06:27
Hi there, I have tried your deployment. However, it works for me. Could you double-check your config and your keys?


https://github.com/okisdev/ChatChat/assets/66008528/cbfcbd80-07ff-404c-8629-ffac49616d2a

**Comment by GabrielRoc** [comment] 2023-08-04 12:31
The problem is happening when making POST type requests in the registration part with email. Variables are set correctly

![image](https://github.com/okisdev/ChatChat/assets/15702931/f067161c-c7bc-4491-8c93-6cba56060270)

![image](https://github.com/okisdev/ChatChat/assets/15702931/e38ccb90-8d6f-4658-babb-2c8ad66720e4)

Please try the registration part of my deploy

**Comment by GabrielRoc** [comment] 2023-08-05 11:24
I synced my fork with yours and re-deployed but that didn't fix the problem, the POSTs persist with 405

**Comment by okisdev** [comment] 2023-08-05 12:31
Sorry for the unexpected behaviour, try v0.0.37 again, it should be fixed properly.

**Closed** 2023-12-04 16:55 UTC
Labels: bug
